version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0

defaults: &defaults
  working_directory: ~/toy_robot_game
  parallelism: 2

  docker:
    - image: cimg/ruby:2.3.0
jobs:
  coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache

      - run: bundle install

      - run:
          name: Merge and check coverage
          command: |
            RUN_COVERAGE=true bundle exec rake simplecov:report_coverage
      - store_artifacts:
          path: ~/toy_robot_game/coverage
          destination: coverage
  build:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
  test:
    <<: *defaults
    steps:
      - checkout
      - ruby/install-deps
      # Run rspec
      - ruby/rspec-test
      - run:
          name: Stash Coverage Results
          command: |
            mkdir coverage_results
            cp -R coverage/.resultset.json coverage_results/.resultset-${CIRCLE_NODE_INDEX}.json
      - persist_to_workspace:
          root: .
          paths:
            - coverage_results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - test
